from django.urls import path

from .domain_views import (
    AIRequestDetailView,
    AIRequestListCreateView,
    BillingRecordListView,
    CompanyDetailView,
    CompanyListView,
    ContractDetailView,
    ContractListView,
    ConversationDetailView,
    ConversationListCreateView,
    ConversationMarkReadView,
    FavoriteDeleteView,
    FavoriteListCreateView,
    FreelancerDetailView,
    FreelancerListView,
    MessageListCreateView,
    MyProfileView,
    NotificationListView,
    NotificationMarkReadView,
    NotificationUnreadCountView,
    OCRResumeParseDetailView,
    OCRResumeParseListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    ProposalListCreateView,
    ReviewListCreateView,
    TimeEntryDetailView,
    TimeEntryListCreateView,
    TransactionListView,
    VerificationSelfView,
)
from .views import CurrentUserView, HealthCheckView, LoginView, RegisterView

urlpatterns = [
    path('health/', HealthCheckView.as_view(), name='health-check'),
    path('auth/me/', CurrentUserView.as_view(), name='current-user'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('profiles/me/', MyProfileView.as_view(), name='my-profile'),
    path('freelancers/', FreelancerListView.as_view(), name='freelancer-list'),
    path('freelancers/<int:pk>/', FreelancerDetailView.as_view(), name='freelancer-detail'),
    path('companies/', CompanyListView.as_view(), name='company-list'),
    path('companies/<int:pk>/', CompanyDetailView.as_view(), name='company-detail'),
    path('projects/', ProjectListCreateView.as_view(), name='project-list-create'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('favorites/', FavoriteListCreateView.as_view(), name='favorite-list-create'),
    path('favorites/<int:pk>/', FavoriteDeleteView.as_view(), name='favorite-delete'),
    path('proposals/', ProposalListCreateView.as_view(), name='proposal-list-create'),
    path('contracts/', ContractListView.as_view(), name='contract-list'),
    path('contracts/<int:pk>/', ContractDetailView.as_view(), name='contract-detail'),
    path('reviews/', ReviewListCreateView.as_view(), name='review-list-create'),
    path('verification/me/', VerificationSelfView.as_view(), name='verification-self'),
    path('notifications/', NotificationListView.as_view(), name='notification-list'),
    path('notifications/unread-count/', NotificationUnreadCountView.as_view(), name='notification-unread-count'),
    path('notifications/<int:pk>/read/', NotificationMarkReadView.as_view(), name='notification-read'),
    path('conversations/', ConversationListCreateView.as_view(), name='conversation-list-create'),
    path('conversations/<int:pk>/', ConversationDetailView.as_view(), name='conversation-detail'),
    path('conversations/<int:pk>/read/', ConversationMarkReadView.as_view(), name='conversation-read'),
    path('conversations/<int:conversation_id>/messages/', MessageListCreateView.as_view(), name='message-list-create'),
    path('time-entries/', TimeEntryListCreateView.as_view(), name='time-entry-list-create'),
    path('time-entries/<int:pk>/', TimeEntryDetailView.as_view(), name='time-entry-detail'),
    path('billing-records/', BillingRecordListView.as_view(), name='billing-record-list'),
    path('transactions/', TransactionListView.as_view(), name='transaction-list'),
    path('ai/requests/', AIRequestListCreateView.as_view(), name='ai-request-list-create'),
    path('ai/requests/<int:pk>/', AIRequestDetailView.as_view(), name='ai-request-detail'),
    path('ai/ocr/resume-parse/', OCRResumeParseListCreateView.as_view(), name='ocr-resume-list-create'),
    path('ai/ocr/resume-parse/<int:pk>/', OCRResumeParseDetailView.as_view(), name='ocr-resume-detail'),
]
